[package]
name = "beam"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.39.2", features = ["full"] }
macella = { git = "https://github.com/MacbClarke/macella", rev = "aecf2a02" }

